POST http://localhost:4000/User/SignUp
Content-Type: application/json

{
        "pNombre": "Johan",
        "sNombre": "Felipe",
        "pApellido": "Ramirez",
        "sApellido": "Beltran",
        "nDocumento": 1055452863,
        "fNacimiento":  "2005-09-27" ,
        "email": "johan@example.com",
        "contrasenia": "aklsjiwj@we12",
        "direccion": "Calle Ficticia 123",
        "nTelefonico": 32100546545,
        "urlFoto": "https://storagalmacenamiento.blob.core.windows.net/imagescontainer/perfiles/perfil/prueba.jpeg?sp=r&st=2025-03-23T20:26:23Z&se=2025-03-24T04:26:23Z&spr=https&sv=2024-11-04&sr=b&sig=cR%2BRynPu8aEj%2FaGvgpO3M7hlKlzSti2%2FtwOii0OL3i0%3D",
        "nombreContainer": "imagescontainer",
        "nombreDirectorio": "perfiles/perfil/prueba.jpeg",
        "tokenAccess": "sp=r&st=2025-03-23T20:34:23Z&se=2025-03-24T04:34:23Z&spr=https&sv=2024-11-04&sr=b&sig=Ses2lLyxCJ9UMPQhePEd%2Fl7RKp326hA9ofwfnNxXNik%3D"
}



### login
POST http://localhost:4000/User/SignIn
Content-Type: application/json

{
    "email":"simonrodriguezospina5870@gmail.com",
    "contrasenia":"simon12345"
}

### Obtener usuario
GET http://localhost:4000/User/SignUp/Usuario/
Content-Type: application/json


### Obtener usuarios
GET http://localhost:4000/User/SignUp/Usuarios/all
Content-Type: application/json


### Actualizar usuario
PUT http://localhost:4000/User/SignUp/Actualizar/
Content-Type: application/json

{
    "numeroCelular":5873225
}

### eliminar usuario
DELETE http://localhost:4000/User/SignUp/Eliminar/67e8b850c8178ddb37feaf50
Content-Type: application/json

### obtetner todos los usuarios
