POST http://localhost:4000/User/SignUp
Content-Type: application/json

{
    "nombre":"Simon",
    "segundoNombre":"David",
    "primerApellido":"Rodriguez",
    "segundoApellido":"Ospina",
    "correo":"simondavidrodriguez5870@gmail.com",
    "contrasena":"1013036309simon",
    "fechaNacimiento":"5 mayo 2008",
    "numeroCelular":3223415969
}

### Obtener usuario
GET http://localhost:4000/User/SignUp/Usuario/
Content-Type: application/json


### Obtener usuarios
GET http://localhost:4000/User/SignUp/Usuarios/all
Content-Type: application/json


### Actualizar usuario
PUT http://localhost:4000/User/SignUp/Actualizar/67dd132f40f1f8598343b5bf
Content-Type: application/json

{
    "numeroCelular":5873225
}

### eliminar usuario
DELETE http://localhost:4000/User/SignUp/Eliminar/67dd130440f1f8598343b5b6
Content-Type: application/json

### obtetner todos los usuarios
